# Generated by Django 5.0.4 on 2024-07-03 11:17

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.unique_generate_code, max_length=8, unique=True),
        ),
    ]
